services:
  grizzpector:
    image: sandmanren/grizzpector:latest
    ports:
      - "3000:3000"
    environment:
      - DISCORD_APP_ID=${DISCORD_APP_ID}
      - DISCORD_PUBLIC_KEY=${DISCORD_PUBLIC_KEY}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    networks:
      - grizzpector-network
    volumes:
      - ./volumes/app/data:/app/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  ngrok:
    image: ngrok/ngrok:latest
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_URL=${NGROK_URL}
    command: http grizzpector:3000 --url=${NGROK_URL}
    networks:
      - grizzpector-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  grizzpector-network:
    driver: bridge
