# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**/*.md"
      - "**/docker.compose.yaml"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "**/*.md"
      - "**/docker.compose.yaml"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.10.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test || echo "no tests found"

  docker:
    # on build success, create and push a docker image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/grizzpector:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/grizzpector:latest
