# on a tag "release-*", checkouts the code, builds the image, tag as "latest"
# and push to the docker registry
name: Build and Push Docker Image on Tag "release-*"

on:
  create:
    tags:
      - "release-*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: ${{secrets.DOCKER_USERNAME}}/grizzpector

    steps:
      - name:  Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and Tag Docker Image
        run: |
          TAG=latest
          echo "Building and tagging as $DOCKER_IMAGE_NAME:$TAG"
          docker build -t $DOCKER_IMAGE_NAME:$TAG .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push $DOCKER_IMAGE_NAME:$TAG
